services:
  web:
    build: .
    container_name: url_shortener_app
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/url_shortener
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./app/configs/.env
    networks:
      - url_shortener_network
      - shared_network
    # develop:
    #   watch:
    #     - action: sync+restart
    #       path: ./app
    #       target: /app

  db:
    image: postgres:17.4
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 30s
      retries: 5
    networks:
      - url_shortener_network

volumes:
  pgdata:

networks:
  url_shortener_network:
    driver: bridge
  shared_network:
    external: true
    name: shared_network