name: Accounts Module Deployment

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: ${{ github.ref_name }}
    steps:
      - name: Get Runner Public IP Address
        uses: candidob/get-runner-ip@v1.0.0
        id: ip

      - uses: actions/checkout@v4


      - name: Create remote directory if it doesn't exist
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_SERVER_IP != '' && secrets.SSH_SERVER_IP || vars.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER != '' && secrets.SSH_SERVER_USER || vars.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_KEY != '' && secrets.SSH_KEY || vars.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            mkdir -p $HOME/mlm_demo/${{ github.event.repository.name }}

      - name: Archive code into zip
        run: |
          zip -r code.zip . -x "target/*"

      - name: Upload zip file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_SERVER_IP != '' && secrets.SSH_SERVER_IP || vars.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER != '' && secrets.SSH_SERVER_USER || vars.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_KEY != '' && secrets.SSH_KEY || vars.SSH_KEY }}
          source: "code.zip"
          target: "$HOME/mlm_demo/${{ github.event.repository.name }}/"

      - name: Deploy code on Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_SERVER_IP != '' && secrets.SSH_SERVER_IP || vars.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER != '' && secrets.SSH_SERVER_USER || vars.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_KEY != '' && secrets.SSH_KEY || vars.SSH_KEY }}
          command_timeout: 15m
          port: 22
          script: |
            cd $HOME/mlm_demo/${{ github.event.repository.name }}/
            shopt -s extglob
            rm -rf -- !(code.zip)
            unzip code.zip
            rm code.zip

      - name: Make env
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_SERVER_IP != '' && secrets.SSH_SERVER_IP || vars.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER != '' && secrets.SSH_SERVER_USER || vars.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_KEY != '' && secrets.SSH_KEY || vars.SSH_KEY }}
          command_timeout: 15m
          port: 22
          script_stop: true
          script: |
            cd $HOME/mlm_demo/${{ github.event.repository.name }}/app/configs/
            rm -f .env
            echo DB_URL=${{ secrets.DB_URL != '' && secrets.DB_URL || vars.DB_URL }} >> .env
            echo DB_HOST=${{ secrets.DB_HOST != '' && secrets.DB_HOST || vars.DB_HOST }} >> .env
            echo DB_PORT=${{ secrets.DB_PORT != '' && secrets.DB_PORT || vars.DB_PORT }} >> .env
            echo DB_NAME=${{ secrets.DB_NAME != '' && secrets.DB_NAME || vars.DB_NAME }} >> .env
            echo DB_USER=${{ secrets.DB_USER != '' && secrets.DB_USER || vars.DB_USER }} >> .env
            echo DB_PASSWORD=${{ secrets.DB_PASSWORD != '' && secrets.DB_PASSWORD || vars.DB_PASSWORD }} >> .env
            
      - name: Run Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_SERVER_IP != '' && secrets.SSH_SERVER_IP || vars.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER != '' && secrets.SSH_SERVER_USER || vars.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_KEY != '' && secrets.SSH_KEY || vars.SSH_KEY }}
          command_timeout: 15m
          port: 22
          script_stop: true
          script: |
            cd $HOME/mlm_demo/${{ github.event.repository.name }}
            ls
            docker compose stop
            docker compose up -d --build --force-recreate
